services:
  - type: web
    name: my-searxng
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SEARXNG_BASE_URL
        value: https://my-searxng.onrender.com/
